version: "3"

services:
  redis:
    image: redis:buster

  web:
    build:
      context: ./web/
      args:
        - BB_BASE_URL=${BB_BASE_URL}
        - BB_PROJECT=${BB_PROJECT}
        - BB_REPORT_SLUG=${BB_REPORT_SLUG}
        - BB_TOKEN=${BB_TOKEN}
    ports:
      - "8000:8000"
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:8080"
      - "443:443"
    links:
      - web
